import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:harness/screens/swarm_screen.dart';
import 'package:harness/state/swarm_catalog.dart';
import 'package:harness/terminal/terminal_binary.dart';
import 'swarm_state_test.dart' show createApp;
import 'swarm_screen_test.dart' show terminal;

void main() {
  testWidgets('machine submenu lists cached agents and opens an exact existing view', (tester) async {
    const channel = MethodChannel('harness/swarm_tabs');
    final messenger = tester.binding.defaultBinaryMessenger;
    final messages = <MethodCall>[];
    messenger.setMockMethodCallHandler(channel, (call) async { messages.add(call); return true; });
    addTearDown(() => messenger.setMockMethodCallHandler(channel, null));
    final app = createApp();
    final input = <TerminalBinaryFrame>[];
    final original = app.activeSwarmId;
    final pane = app.adoptSessionForTest(terminal('a0', input));
    app.newSwarm(name: 'Second');
    final projects = SwarmProjectStore();
    await tester.pumpWidget(MaterialApp(home: SwarmScreen(notifier: app, nativeTabs: true, projectStore: projects)));
    await tester.pump();
    final snapshot = messages.lastWhere((c) => c.method == 'update').arguments as Map;
    final machine = (snapshot['machines'] as List).single as Map;
    expect(machine['agentCount'], 70);
    final rows = machine['agents'] as List;
    expect(rows.first['id'], 'a0');
    expect(rows.first['title'], 'Agent 0');
    expect(rows.first['canOpen'], isTrue);
    final reply = Completer<void>();
    messenger.handlePlatformMessage(channel.name, const StandardMethodCodec().encodeMethodCall(const MethodCall('machineAgent', {'machineId': 'm', 'agentId': 'a0'})), (_) => reply.complete());
    await tester.pumpAndSettle();
    await reply.future;
    expect(app.activeSwarmId, original);
    expect(app.focusedPane, same(pane));
    expect(input, isEmpty);
    final stale = Completer<void>();
    messenger.handlePlatformMessage(channel.name, const StandardMethodCodec().encodeMethodCall(const MethodCall('machineAgent', {'machineId': 'm', 'agentId': 'removed'})), (_) => stale.complete());
    await tester.pumpAndSettle();
    await stale.future;
    expect(app.focusedPane, same(pane));
    expect(app.swarms, hasLength(2));
    await tester.pumpWidget(const SizedBox());
    app.dispose();
    projects.dispose();
  });
}
