// Generated by scripts/gen_roboto_fonts.py. Do not edit.
#pragma once
#include "terminal.h"
extern const ht_pfont_t ht_lv_roboto_med_38;
extern const ht_pfont_t ht_lv_roboto_med_32;
extern const ht_pfont_t ht_lv_roboto_med_28;
extern const ht_pfont_t ht_lv_roboto_reg_38;
extern const ht_pfont_t ht_lv_roboto_reg_25;
extern const ht_pfont_t ht_lv_roboto_reg_20;
extern const ht_pfont_t ht_lv_roboto_med_24;
extern const ht_pfont_t ht_lv_roboto_med_22;
